# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGhActions < Formula
  desc "A sample go app testing GitHub Actions & GoReleaser."
  homepage "https://github.com/lgdd/go-gh-actions"
  version "1.2.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.4/go-gh-actions_1.2.4_darwin_amd64.tar.gz"
      sha256 "a36c62543d773fc8c4ef692f57a30189b1f82fcec63c3347ed74e1555a1bc422"
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.4/go-gh-actions_1.2.4_darwin_arm64.tar.gz"
      sha256 "0c1038db3bbe9342ca64658da53f698336611c69af88e894fe7139528883e1b6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.4/go-gh-actions_1.2.4_linux_amd64.tar.gz"
      sha256 "d3a9201ad39d33d74d15fb7af97d3af37b5081d2548a5840617315ae59def137"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.4/go-gh-actions_1.2.4_linux_arm64.tar.gz"
      sha256 "c8a3b5885f6b08827d03fcf896047b811423f796fef2905c4853ca269d41fbe0"
    end
  end

  def install
    bin.install "go-gh-actions"
  end
end
