# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGhActions < Formula
  desc "A sample go app testing GitHub Actions & GoReleaser."
  homepage "https://github.com/lgdd/go-gh-actions"
  version "1.2.5"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.5/go-gh-actions_1.2.5_macOS_64-bit.tar.gz"
      sha256 "fb50c4e7ffee27ab20e7b3b1a546f06dfc0af78e9a78094d940a9ec0cdafb1df"
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.5/go-gh-actions_1.2.5_macOS_arm64.tar.gz"
      sha256 "20035a2232fbc35c984f294dd7ce43e20fb7165af2f2eef9a8aea50aa6919ce9"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.5/go-gh-actions_1.2.5_linux_64-bit.tar.gz"
      sha256 "3b92dc91238528bcd2f619d2e1d8d762ff8294a5221c951d0af00e18b839f36d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.5/go-gh-actions_1.2.5_linux_arm64.tar.gz"
      sha256 "17553c890504edbcd2c403caf5b90c1b310ef83c2ac0e5f4e4ebbc2006ade0f2"
    end
  end

  def install
    bin.install "go-gh-actions"
  end
end
