# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGhActions < Formula
  desc "A sample go app testing GitHub Actions & GoReleaser."
  homepage "https://github.com/lgdd/go-gh-actions"
  version "1.2.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.6/go-gh-actions_1.2.6_macOS_64-bit.tar.gz"
      sha256 "9b4f6eb5adb665ef0f0c9a344ab6351c245a18db2f337f6f2883e3fb4e7cc8ec"
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.6/go-gh-actions_1.2.6_macOS_arm64.tar.gz"
      sha256 "b1bc210f76eca404f33fb626cb25d1024a3af34b281d630be37e20dfb987d54d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.6/go-gh-actions_1.2.6_linux_64-bit.tar.gz"
      sha256 "33acaa501c698338bbfbd9e724ea16ebcd347e9fe2897b1b20d4b67f010dcf42"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.6/go-gh-actions_1.2.6_linux_arm64.tar.gz"
      sha256 "cbf8968f00a9a7864b5f20309678ac554d6ef98f0155ed483ba1a9dab652dee3"
    end
  end

  def install
    bin.install "goghactions"
  end
end
