# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goghactions < Formula
  desc "A sample go app testing GitHub Actions & GoReleaser."
  homepage "https://github.com/lgdd/go-gh-actions"
  version "1.2.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.6/go-gh-actions_1.2.6_macOS_64-bit.tar.gz"
      sha256 "7683e1207027c54a9b5d6d6faab8453084b763a439c338c34da8dcac63107923"
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.6/go-gh-actions_1.2.6_macOS_arm64.tar.gz"
      sha256 "9cd67011cd02c54a713635d43c9319b0a84c7534d5beb9a4187c6d2c0e963f2b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.6/go-gh-actions_1.2.6_linux_64-bit.tar.gz"
      sha256 "5e921fc9d5001da8b63466c2fc10701093f7c197b683a9eb9cd9cb6a5283b39d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.6/go-gh-actions_1.2.6_linux_arm64.tar.gz"
      sha256 "e41642f3ea6ff5efb1250984dcb579d84cbfe26606b31a8aad734d29cf62703d"
    end
  end

  def install
    bin.install "goghactions"
  end
end
